resolver: lts-9.21
packages:
- '.'
- location:
    git: https://github.com/paullucas/hosc.git
    commit: fe9343ed61d497619e659cf21d468fb6c54dd232
  extra-dep: true
- location:
    git: https://github.com/paullucas/hsc3.git
    commit: 05db5ad3e8b6e260acae06445ca41cd72c4e28d0
  extra-dep: true
- location:
    git: https://github.com/paullucas/hsc3-lang.git
    commit: 627d2118f518bb109723e00c088b4fda9340d78c
  extra-dep: true